### ISSUE TITLE
UseSqlServer extension method configuration error

### ISSUE THREAD

**Issue by cuctc** [rebus-org/Rebus.Recipes#1]
I like the idea of using the "recipe" to simplify/standardize configuration when using Sql Server as the transport, however this recipe causes an error because it attempts to set the Timeout Manager. Seems like that line should be removed from the recipe at this point. 

The error is:
Attempted to register primary -> Rebus.Timeouts.ITimeoutManager, but a primary registration already exists: primary -> Rebus.Timeouts.ITimeoutManager

**Comment by mookid8000** [comment]
I like the idea of "recipes" too – that's almost always what I end up with when using Rebus myself or when working with clients: A Rebus configuration NuGet package with "recipes" for the different types of Rebus endpoints that one needs when working with it, e.g. looking like this:

    var client = Configure.With(...)
        .AsClient()
        .Routing(r => r.TypeBased().Map<string>("input-queue"))
        .Start();

    Configure.With(...)
        .AsServer("input-queue")
        .Start();

where `AsClient` and `AsServer` are configuration extensions that configure transport and persistence from various appsettings laid out by convention.

I am not sure I like the current `Rebus.Recipes` package though, mostly because it depends on SQL Server without being explicit about it – but also because I believe that [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)ing your configuration code is a task you must undertake yourself as natural part of creating a project, it is not something that anyone else can do for you.

Unless someone puts some really good arguments forth, I will remove the `Rebus.Recipes` repository from `rebus-org` soon. If anyone feels like stepping up and taking responsibility for it, I will happily transfer ownership of the repository.
